### ISSUE TITLE
Add infix syntax like Haskell et. al.

### ISSUE THREAD

**Issue by andrew-johnson-4** [andrew-johnson-4/LSTS#153]
**Is your feature request related to a problem? Please describe.**
```lsts
(a `xor` b) `lshift` 3
```

**Describe the solution you'd like**
More sugar please.

**Comment by XChy** [comment]
There is an algorithm called **Pratt Parsing** , which can be applied to avoid multiple repeated discussions of the precedence of different operators. Maybe this issue can be solved by this algorithm?

**Comment by andrew-johnson-4** [comment]
The Haskell wiki doesn't mention what precedence the infix operators get: https://wiki.haskell.org/Infix_operator. I personally don't have much opinion about what precedence it ends up with.

**Comment by XChy** [comment]
I see. But any operator in **expr** must have a precedence, or we can let its precedence be the lowest, in this case where we just parse infix after addsub_term.

Or we can just force `lhs infix rhs` to be surrounded with parentheses.

**Comment by XChy** [comment]
And if the former is OK, I think it's easy for me to implement.

**Comment by andrew-johnson-4** [comment]
Almost any operator precedence for this would be great. The highest expression precedence is [atomic](https://github.com/andrew-johnson-4/LSTS/blob/main/src/ll.rs#L905). The lowest expression precedence is [term](https://github.com/andrew-johnson-4/LSTS/blob/main/src/ll.rs#L1230). I would like to keep atomic as the highest precedence. I would also like to keep the name of the lowest precedence the same, but it is ok to just redirect to whatever rule is actually lowest.

**Comment by XChy** [comment]
> I see. But any operator in **expr** must have a precedence, or we can let its precedence be the lowest, in this case where we just parse infix between prefix_term and atom_term.
> 
> Or we can just force `lhs infix rhs` to be surrounded with parentheses.

Sorry, I messed up here. **lowest** should be replaced by **hightest**.
After consideration, I'd like to insert `ll1_prefix_term` between `ll1_power_term` and `ll1_atom_term`.
