### ISSUE TITLE
Cannot run the basic example of LSTS

### ISSUE THREAD

**Issue by XChy** [andrew-johnson-4/LSTS#206]
**Describe the bug**
Cannot run the basic example of LSTS

**To Reproduce**
Filename: a.tlc
Code:
```
1;
3.0;
"abc";
2 + 3;
"[" + [for x in range(1,25) yield x^3].join(",") + "]";
```

Command:
```
lsts run a.tlc
```

**Screenshots**
![image](https://github.com/andrew-johnson-4/LSTS/assets/31238849/f45f0b85-536b-451a-9ca7-0a56d11b03f2)

**Result**
![image](https://github.com/andrew-johnson-4/LSTS/assets/31238849/1e92e0f0-674a-4700-a78d-4ebd986ec91f)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by andrew-johnson-4** [comment]
Thanks for the report. Looks like `preludes` folder is not on the path for some reason. I'll look into it.

**Comment by andrew-johnson-4** [comment]
Note, tuples and lists are the same thing now. There is no special syntax for `[1,2,3]` vs `(1,2,3)`. The example above should be:

```
1;
3.0;
"abc";
2 + 3;
"[" + (for x in range(1,25) yield x^3).join(",") + "]";
```

otherwise the fix should be merged tonight hopefully.

**Comment by andrew-johnson-4** [comment]
This also reminded me that floating point integers are not fully supported yet. I will open a separate issue for that. So the final proposed solution here is:

1. Install the latest version of LSTS

`cargo install lsts`

2. Save your program to a.tlc

```lsts
1;
"abc";
2 + 3;
"[" + (for x in range(1,25) yield x^3).join(",") + "]";
```

3. Run a.tlc with the JIT compiler

`lsts run a.tlc`

4. The expected output should be

`"[1,8,27,64,125,216,343,512,729,1000,1331,1728,2197,2744,3375,4096,4913,5832,6859,8000,9261,10648,12167,13824]"`

This has been tested with Ubuntu 20.04.2 LTS.

Let me know if this works for you and whether you consider this solution as resolved. Thanks for your cooperation!

**Comment by XChy** [comment]
It seems to work well.
![image](https://github.com/andrew-johnson-4/LSTS/assets/31238849/b690924a-3c90-4430-9ef0-0b74f6e2e820)

**Comment by XChy** [comment]
And maybe you need to update your reference website:
![image](https://github.com/andrew-johnson-4/LSTS/assets/31238849/d1019c63-0188-42c2-8192-99b280c9dcf1)
