### ISSUE TITLE
Simple Compiler targeting LLVM IR

### ISSUE THREAD

**Issue by andrew-johnson-4** [andrew-johnson-4/LSTS#220]
**Is your feature request related to a problem? Please describe.**
L1 is going to be our host language for bootstrap compilers.
It is meant to be entirely user facing and as such is nice to work with.

**Describe the solution you'd like**
Compile some LM programs to binary through LLVM IR.

**Describe alternatives you've considered**
LM is not nice to program in directly.

**Comment by XChy** [comment]
I'm familiar with LLVM, but unfamiliar with Rust. I figure that we need to depend on some **LLVM-Binding for Rust** here, such as llvm-sys and Inkwell. Then we have to codegen different AST, which also requires conversion from the type of LSTS to the type of LLVM.

**Comment by XChy** [comment]
It's also suggested to add an option `--emit-llvm`  into command tool, which shows IR.

**Comment by andrew-johnson-4** [comment]
I was thinking of generating IR and having [llc](https://releases.llvm.org/9.0.0/docs/CommandGuide/llc.html#:~:text=llc%20-%20LLVM%20static%20compiler%20%C2%B6%201%20SYNOPSIS,will%20from%20filename.%20...%204%20EXIT%20STATUS%20%C2%B6) compile that.

**Comment by andrew-johnson-4** [comment]
The self-hosting compiler won't have access to Rust bindings, so it needs to make the jump to lower level more directly.

**Comment by XChy** [comment]
It may be too hard and slow to generate IR text(harder even for bitcode) ourselves.
Besides, there must be a linker and runtime to link and run the object files that llc generates.

**Comment by andrew-johnson-4** [comment]
The bootstrap compiler is intended to only compile a small minimal version of our compiler, which is then used to compile the "good" compiler. It is ok to be inefficient suboptimal here. I figure that text files and command line utilities are really stable and easy to work with, so they're perfect.

For the good compiler we will link directly to LLVM libraries that we need to do codegen.

**Comment by andrew-johnson-4** [comment]
Thinking about this some more, the lsts bootstrap just sends data to lm. Lm can use rust bindings or whatever is most convenient. The bootstrap here should implement some idea from lm or lsts, but lm gets to make the final decision about lowering.

**Comment by andrew-johnson-4** [comment]
Tomorrow I will make a new ticket. This one is confused and misguided.

**Comment by XChy** [comment]
I see.
